---
- name: Create vagrant user with predefined password
  ansible.builtin.user:
    name: "vagrant"
    create_home: true
    shell: "/bin/bash"
    password: "$6$3rtaXePeRZrLePT/$NRkB3ZyNdwabzbQU2H3KqgahWPgZa5dwwsx8I22BfmIdgFYP.JaBli8PGSVaa1QoEHFOVoahfjEnPPYQryoEY/"

- name: Add insecure vagrant public key
  ansible.posix.authorized_key:
    user: vagrant
    key: "{{ pve_vagrant__vagrant_key_url }}"
    exclusive: true
    manage_dir: true
    state: present

- name: Install SUDO package
  ansible.builtin.package:
    name: sudo
    state: present

- name: Setup sudoers for vagrant user
  ansible.builtin.copy:
    src: "vagrant-sudoers"
    dest: "/etc/sudoers.d/vagrant"
    owner: root
    group: root
    mode: "0440"
    backup: false
