- name: Apt repos | Remove enterprise repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    state: absent
    components: "{{ item.components }}"
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
  loop: "{{ pve_vagrant__deb822_del_repos[ansible_distribution_major_version] }}"

- name: Apt repos | Add no-subscription repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    state: present
    components: "{{ item.components }}"
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
  loop: "{{ pve_vagrant__deb822_add_repos[ansible_distribution_major_version] }}"
