---
# tasks file for pve-vagrant
- name: Setup vagrant user
  ansible.builtin.import_tasks:
    file: 10_vagrant_user.yml

- name: Setup root user
  ansible.builtin.import_tasks:
    file: 11_root_user.yml

- name: Setup repositories
  ansible.builtin.import_tasks:
    file: 20_apt_repos.yml

- name: Configure network
  ansible.builtin.import_tasks:
    file: 30_network_config.yml

- name: Upgrade OS and reboot machine to activate new kernel
  when: >
    pve_vagrant__system_upgrade == "YES"
  ansible.builtin.import_tasks:
    file: 40_upgrade.yml

- name: Clear cache and free unused space
  ansible.builtin.import_tasks:
    file: 50_compact.yml
