---
# tasks file for pve-vagrant
- name: Create vagrant user with predefined password
  ansible.builtin.user:
    name: "vagrant"
    create_home: true
    shell: "/bin/bash"
    password: "$6$3rtaXePeRZrLePT/$NRkB3ZyNdwabzbQU2H3KqgahWPgZa5dwwsx8I22BfmIdgFYP.JaBli8PGSVaa1QoEHFOVoahfjEnPPYQryoEY/"

- name: Add insecure vagrant public key
  ansible.posix.authorized_key:
    user: vagrant
    key: "{{ pve_vagrant__vagrant_key_url }}"
    exclusive: true
    manage_dir: true
    state: present

- name: Setup sudoers for vagrant user
  ansible.builtin.copy:
    src: "vagrant-sudoers"
    dest: "/etc/sudoers.d/vagrant"
    owner: root
    group: root
    mode: "0440"
    backup: false

- name: Remove enterprise repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: false
    state: absent
  loop:
    - deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
    - deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} enterprise

- name: Add no-subscription repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    filename: "pve-no-subscription.list"
    update_cache: false
    state: present

- name: Install SUDO package
  ansible.builtin.package:
    name: sudo
    state: present

- name: Revert old fashion names for network interfaces (ethXX)
  ansible.builtin.copy:
    src: "grub-network-interfaces.cfg"
    dest: "/etc/default/grub.d/network-interfaces.cfg"
    owner: root
    group: root
    mode: "0644"
    backup: false
  notify: Rebuild GRUB config

- name: Configure system network interfaces
  ansible.builtin.copy:
    src: "etc-network-interfaces"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: "0644"
    backup: false

- name: Upgrade OS and reboot machine to activate new kernel
  when: >
    pve_vagrant__system_upgrade == "YES"
  block:
    - name: Dist-upgrade OS
      ansible.builtin.apt:
        update_cache: true
        upgrade: "dist"

    - name: Reboot virtual machine
      ansible.builtin.reboot:

- name: Copy script for compactifiyng
  ansible.builtin.copy:
    src: "zeroing.sh"
    dest: "/usr/local/sbin/zeroing.sh"
    owner: root
    group: root
    mode: "0750"

- name: Execute compactifiyng script
  ansible.builtin.command:
    cmd: "/usr/local/sbin/zeroing.sh"
  changed_when: false
