---
# tasks file for pve-vagrant
- name: Setup vagrant user
  ansible.builtin.import_tasks:
    file: vagrant_user.yml

- name: Setup repositories
  ansible.builtin.import_tasks:
    file: apt_repos.yml

- name: Configure network
  ansible.builtin.import_tasks:
    file: network_config.yml

- name: Upgrade OS and reboot machine to activate new kernel
  when: >
    pve_vagrant__system_upgrade == "YES"
  ansible.builtin.import_tasks:
    file: upgrade.yml

- name: Clear cache and free unused space
  ansible.builtin.import_tasks:
    file: compact.yml
